# Welcome to Jekyll!
# coding: utf-8
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
name: Zehua Li
description: Nifty little description

# Site settings
title: LiZehua.log
email: leezehua@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ZehuaLee.github.io" # the base hostname & protocol for your site
twitter_username: ritakuka
github_username:  ZehuaLee
codepen_username: codepen_Li
facebook_username: Li Zehua
vk_username: vk_Li
avatar: yes
avatar_img_path: "http://avatars2.githubZehuaLee.com/u/17301305"

front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img_path: "imgs/favicon.ico"
# Build settings
markdown: kramdown
permalink: pretty
